apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/AbhiVastrad/myrailsapp-config
      type: git
      name: myrailsapp

